name: CI - Multi App Aqua Scan

on: [push, pull_request]

jobs:
  scan:
    name: Aqua Code Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Aqua Scanner - Trivy FS
        uses: docker://aquasec/aqua-scanner
        with:
          args: trivy fs --sast --scanners config,vuln,secret .
        env:
          AQUA_KEY: ${{ secrets.AQUA_KEY }}
          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
          GITHUB_TOKEN: ${{ github.token }}
          AQUA_URL: https://api.eu-1.supply-chain.cloud.aquasec.com
          CSPM_URL: https://eu-1.api.cloudsploit.com
          TRIVY_RUN_AS_PLUGIN: 'aqua'

  build-and-sbom:
    name: Build & SBOM for Each App
    runs-on: ubuntu-latest
    needs: scan
    strategy:
      matrix:
        app: [app1, app2]
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t knightfortheright/${{ matrix.app }}:${{ github.sha }} ./${{ matrix.app }}
      - name: Generate SBOM
        run: |
          export BILLY_SERVER=https://billy.eu-1.codesec.aquasec.com
          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
          if ! cat install.sh.checksum | sha256sum ; then
            echo "install.sh checksum failed"
            exit 1
          fi
          BINDIR="." sh install.sh
          rm install.sh install.sh.checksum
          ./billy generate \
            --access-token "${{ secrets.GITHUB_TOKEN }}" \
            --aqua-key "${{ secrets.AQUA_KEY }}" \
            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
            --cspm-url https://eu-1.api.cloudsploit.com \
            --artifact-path knightfortheright/${{ matrix.app }}:${{ github.sha }}
